# Generated by Django 3.2.3 on 2021-05-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devTest1', '0003_categorymenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='insights',
            name='has_video',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
