# Generated by Django 3.2.3 on 2021-05-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devTest2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimage',
            name='imageName',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
