# Generated by Django 3.2.3 on 2021-05-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devTest2', '0002_backgroundimage_imagename'),
    ]

    operations = [
        migrations.CreateModel(
            name='breadcrumbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumbName', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
