# Generated by Django 3.2.3 on 2021-05-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devTest2', '0004_frames'),
    ]

    operations = [
        migrations.CreateModel(
            name='headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headlineHeader', models.CharField(blank=True, max_length=254, null=True)),
                ('headlineQuote', models.CharField(blank=True, max_length=254, null=True)),
                ('headlineName', models.CharField(blank=True, max_length=254, null=True)),
                ('headlineEducation', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
